### ISSUE TITLE
Opening the sourcekit-lsp package takes about 5 seconds to initialize until LSP-based functionality starts to be come available

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/sourcekit-lsp#1181]
Oh, sorry. Taking this back. The issue appears to be that initializing sourcekit-lsp takes about 3 seconds when opening sourcekit-lsp and opening the first document takes another 2 seconds (SwiftPM is doing something around dependency loading). Attaching a log of sourcekit-lsp serve initialization. 

Possible solutions here could include:
- Figure out why initializing the `SwiftPMWorkspace` takes 3 seconds during initialization
- Not wait for the initialization of `SwiftPMWorkspace` to finish before returning from the `InitializeRequest`
- Figure out why we are doing package loading during the `textDocument/didOpen` notification
- Time out during build settings retrieval, open file with fallback build settings and re-open it when real build settings become available.

It could also be that this is competing for the build directory lock with package loading that is started by the Swift extension, which means that package initialization can’t start until that package resolve is done.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://126644596

**Comment by adam-fowler** [comment]
Competing for the lock sounds very possible.

**Comment by ahoppen** [comment]
I don’t think that’s related. The issue is about `SwiftPMWorkspace` doing work (like resolving package dependencies) and SourceKit-LSP shouldn’t get into that path if your project doesn’t have a `Package.swift`.

**Comment by ahoppen** [comment]
Should be fixed by https://github.com/swiftlang/sourcekit-lsp/pull/1632.
