### ISSUE TITLE
Figure out how to do background preparation for projects with a BSP build server

### ISSUE THREAD

**Issue by ahoppen** [swiftlang/sourcekit-lsp#1226]
To index a target, we need to prepare it (which builds all the Swift modules of its dependencies) and for that we probably need a BSP request to prepare a target. For that, we would probably need to introduce a new BSP request or, alternatively, build the entire target, which will perform unnecessary work like building object files. 

We need to design how this interaction should work.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://127606323

**Comment by SolaWing** [comment]
I use https://github.com/SolaWing/xcode-build-server, which provide compiler flags to LSP. It currently does not implement the association of target and source files, but this can be improved if necessary

**Comment by ahoppen** [comment]
Just wanted to share a quick update here that adding support for target preparation in BSP is mostly a matter of taking time to design the interface in a clean way so we can continue supporting it in a stable manner going forward. Doing so is out of scope for Swift 6.0 but valuable for a later release.
