### ISSUE TITLE
No source generated by Add test target refactoring on Windows

### ISSUE THREAD

**Issue by award999** [swiftlang/sourcekit-lsp#1430]
### Swift version

swift-6.0-DEVELOPMENT-SNAPSHOT-2024-06-03

### Platform

Windows 11

### Editor

Visual Studio Code with development swift extension

### Does the issue reproduce with Swift 6?

Yes

### Description

Source code is not generated by the Add test target refactoring on Windows

### Steps to Reproduce

In the Package.swift for any project, run either variant of the Add test target refactoring. The dependencies and targets are updated in the Package.swift but the Test folder and example test source is not generated. Only seeing this on Windows

**Comment by ahoppen** [comment]
@award999 confirmed offline that the issue no longer reproduces.
