### ISSUE TITLE
Code autocompletion stop working after specify SDK

### ISSUE THREAD

**Issue by leozhao0709** [swiftlang/sourcekit-lsp#1587]
**Describe the bug**
As long as I specify the SDK to iOS in settings or use "Select target platform" to select iOS, then code completion is stop working. Seems currently only MacOS SDK is working for me....

**To Reproduce**
1. create a swift package by using xcode. And then create a simple swiftui view:

```swift
// Sources/MyLibrary/MyLibrary.swift

import SwiftUI

public struct MyLibraryView: View {
  public init() {}  // Add an initializer if needed

  public var body: some View {
    VStack {
      Text("Hello, iOS!")
        .frame(width: 100, height: 100, alignment: .center)
    }
  }
}

```

2. specify the sdk path to simulator sdk or use "Select target platform" to select iOS
3. All the code completion is stop working
4. I am not seeing any errors in output

**Expected behavior**
The code completion should always working not matter what sdk are using.

**Environment**
 - OS: macOS Sonoma version 14.4.1 (I am using m2 macbook pro laptop) 
 - Swift version (output of `swift --version`) 
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
 - Visual Studio Code version: Version: 1.89.1 
 - vscode-swift version: 1.9.0

**Additional context**
NA

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://132484681

**Comment by ahoppen** [comment]
VS Code adds the following parameters to `sourcekit-lsp` when launching it

```
-Xswiftc -sdk -Xswiftc /Applications/RainbowE.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk -Xswiftc -target -Xswiftc arm64-apple-ios17.4
```

This generates build settings like the following

```
…
-sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk
-F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks
-I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib
-L /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib
-g
-sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS17.4.sdk
-target arm64-apple-ios17.4
-Xcc
-isysroot
-Xcc /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.4.sdk
-Xcc
-F
-Xcc /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks
-Xcc
-fPIC
-Xcc
-g
```

Setting aside that the compiler arguments still contain the macOS SDK, which will get overwritten, it is missing `-F, `-I`, `-L`, `-Xcc -isysroot`, and `-Xcc -F` search paths into the iOS SDK.

The proper solution here is that VS Code shouldn’t pass additional command line options to SourceKit-LSP and instead SourceKit-LSP needs some way of configuring the iOS SDK to be used.

**Comment by leozhao0709** [comment]
Hello, is there any updates for the issue? Thanks.

**Comment by kabiroberai** [comment]
The VSCode extension's "Select Target Platform" is somewhat hacky at the moment — I'm thinking of making a PR to have it initialize SourceKit-LSP the right way instead. Try resetting the VSCode SDK setting and saving the following file as `.sourcekit-lsp/config.json` (see also: [Configuration File](https://github.com/swiftlang/sourcekit-lsp/blob/d11c101ce210ad23f917cf06fb13a7d9e243872b/Documentation/Configuration%20File.md) docs):
```json
{
    "swiftPM": {
        "triple": "arm64-apple-ios",
        "swiftCompilerFlags": [
            "-sdk",
            "/var/db/xcode_select_link/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
        ],
        "cCompilerFlags": [
            "-isysroot",
            "/var/db/xcode_select_link/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
        ]
    }
}
```
This should be able to handle most iOS packages. Further the need for `{swift,c}CompilerFlags` would go away if we landed https://github.com/swiftlang/swift-package-manager/pull/6828 (and potentially made some changes in this repo too) but this should do the trick for now.

**Comment by kabiroberai** [comment]
I think GitHub was a bit trigger-happy about automatically closing this issue after #1643 landed — we'd actually also need https://github.com/swiftlang/swift-package-manager/pull/6828 in order to avoid the explicit compiler flag settings. That said this can be considered resolved if setting the compiler flags is okay.

**Comment by marvin-yorke** [comment]
> saving the following file as `.sourcekit-lsp/config.json`
I've been poking around this config file for a while, but your suggestion finally made it work for me in Zed, thanks a lot!
