### ISSUE TITLE
Don't work with plugin generated code

### ISSUE THREAD

**Issue by yaroslavyaroslav** [swiftlang/sourcekit-lsp#1624]
### Swift version

swiftlang-6.0.0.7.6 clang-1600.0.24.1

### Platform

macOS 15

### Editor

Sublime Text 4

### Does the issue reproduce with Swift 6?

Yes

### Description

`sourcekit-lsp` fails to provide code completion for plugin generated code. It fails in either mode regardless of is background indexing enabled or not. Tested on ST4, but as if it's server problem it should reproduce in any editor of choice.

### Steps to Reproduce

0. Install on sublime text `LSP` and `LSP-Sourcekit` packages.
1. `clone git@github.com:apple/swift-openapi-generator.git`
2. `cd swift-openapi-generator/Examples/hello-world-urlsession-client-example/`
3. `subl .`
4. Open the only presented swift file in project `Sources/HelloWorldURLSessionClient/HelloWorldURLSessionClient.swift` within editor.
5. if background-indexing is enabled — wait till it finishes. If it's not, build the project.
6. Restart the `sourcekit-lsp` server.

Completion and type hinting works for user defined types and types from stdlib, but not for Client object, which is generated by plugin.

### Logging

[sourcekit-lsp.log](https://github.com/user-attachments/files/16603457/sourcekit-lsp.log)

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://133778179

**Comment by ahoppen** [comment]
This appears to be the same issue as https://github.com/swiftlang/sourcekit-lsp/issues/665, which also contains a [workaround](https://github.com/swiftlang/sourcekit-lsp/issues/665#issuecomment-2093169169)
