### ISSUE TITLE
List of tests shown in VS Code's Test Explorer is incomplete

### ISSUE THREAD

**Issue by stmontgomery** [swiftlang/sourcekit-lsp#1667]
### Swift version

swiftlang-6.0.0.9.11

### Platform

macOS 14.5

### Editor

VS Code with Swift extension v1.11.0

### Does the issue reproduce with Swift 6?

Yes

### Description

When opening the swift-testing package in VS Code with Swift extension v1.11.0, the list of tests shown in the Test Explorer is very incomplete and lacks all Swift Testing style tests. It only includes the handful of XCTestCase subclasses which exist in the project.

This is for the `TestingTests` target of that package; the `TestingMacrosTests` target is complete.

### Steps to Reproduce

1. Open the swift-testing package in VS Code with this configuration
2. Open the Test Explorer
3. See that the `TestingTests` target's list of tests is incomplete.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://135984909

**Comment by ahoppen** [comment]
Should have been fixed by https://github.com/ahoppen/sourcekit-lsp/commit/3d953750430eda85b8bef32b8e223e5a008c9a60#diff-fdb0d2e4e192a73ab75b193c3a9cbadda5365e471d2aa135cd346c825d7f1abd.
