### ISSUE TITLE
Test functions in classes extending XCTestSuite erroneously included as tests

### ISSUE THREAD

**Issue by plemarquand** [swiftlang/sourcekit-lsp#1694]
### Swift version

swiftlang-6.0.0.9.10

### Platform

macOS 15.0

### Editor

VS Code

### Does the issue reproduce with Swift 6?

Yes

### Description

When a class in a test target inherits from **`XCTestSuite`**, not XCTestCase, methods inside of it that match the naming convention of tests are erroneously returned as tests in the `workspace/tests` and `textDocument/tests` requests.

### Steps to Reproduce

The following code reports both `Suite` and `testFoo` as something that can be run, but doing `swift test --filter TestTarget.Suite/testFoo$` results in no tests being run.

```swift
class Suite: XCTestSuite {
    func testFoo() {}
}
```

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://136362710

**Comment by ahoppen** [comment]
This behaves as intended. The syntactic test scanner doesn’t know that `XCTestSuite` doesn’t inherit from `XCTestCase` (you could have added `class XCTestSuite: XCTestCase {}` somewhere in the module) and thus errors on the side of reporting it. 

Once the semantic index catches up through background indexing or a build, we know that `Suite` doesn’t inherit from `XCTestCase` and we stop returning the test.

**Comment by plemarquand** [comment]
Makes sense, I actually see the same behaviour in Xcode.
