### ISSUE TITLE
sourcekit-lsp creates temporary folders and never deletes them

### ISSUE THREAD

**Issue by DimaKozhinov** [swiftlang/sourcekit-lsp#1698]
### Swift version

6.0

### Platform

Windows 11

### Editor

Any editor, e.g. VS Code

### Does the issue reproduce with Swift 6?

Yes

### Description

Every time when sourcekit-lsp.exe is opening a document, it creates a temporary folder like this:
`C:\Users\username\AppData\Local\Temp\TemporaryDirectory.XXXXXX`
where username is Windows user name, and XXXXXX is a string of random letters and digits.
These folders are never deleted and continue to be added.

### Steps to Reproduce

Open a folder (document) containing some Swift project with VS Code. A temporary folder is created.
Close the folder (document) in VS Code. The temporary folder is not deleted.
Close VS Code. The temporary folder is not deleted.
Repeat the steps above. A new temporary folder is added and never deleted.

The issue is not related to VS Code, as it is also reproduced in my custom editor which uses sourcekit-lsp.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://136394581

**Comment by ahoppen** [comment]
I just traced this down and in my case it was not SourceKit-LSP that created these directories, but the Swift driver. I filed https://github.com/swiftlang/swift-driver/issues/1720 to keep track of that and I assume that’s what you’re seeing as well. 

@DimaKozhinov, to verify there is no other cause for these temporary directories on your machine, could you check if the temporary directories you are seeing all have a `.keep-directory` file in it, which indicates they were created by the driver? If that’s not the case, please re-open the issue and we can investigate that further.

**Comment by DimaKozhinov** [comment]
Checked with Swift 6.0.1, these temporary directories all have a zero-sized `.keep-directory` file.

**Comment by ahoppen** [comment]
OK, then this is https://github.com/swiftlang/swift-driver/issues/1720.
