### ISSUE TITLE
Support for projects not using SwiftPM

### ISSUE THREAD

**Issue by ADKaster** [swiftlang/sourcekit-lsp#1708]
### Description

Recent versions of CMake allow building Swift and C++ code in the same project.

The support is still immature and needs specific handling in the CMake to properly take advantage of all features, and to be cross-platform friendly.

However, it's still workable and can produce working code. I'm just not sure how to allow SourceKit-LSP (via the Swift plugin for VsCode) to properly parse this mixed-language project.

I have the following constraints:
- clangd loads the compile_commands.json from path/to/build rather than the project root directory via reading `.clangd` , which looks something like this:
   ```
   CompileFlags:
    CompilationDatabase: relative/path/to/binary/dir
   ```
- clangd can't load the compile-commands for .swift files. Since sourcekit-lsp is built on top of clangd, in theory it adds file-type matching for .swift files and handles this?

I guess my real question is, can I use SourceKit-LSP as a "Clangd+Swift" language server, with all the features of clangd for C++/ObjC++ code, and additional support for Swift? Or is there some serious architectural wrangling needed to support swift compile commands from a compile_commands.json?

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://136510115

**Comment by ahoppen** [comment]
SourceKit-LSP is able to provide functionality for both Swift and C-family files based on `compile_commands.json` generated by CMake and that should work out of the box. Do you have the clangd plugin installed in VS Code? If so, you should disable it and let SourceKit-LSP provide the functionality for your C++ files because it knows how to integrate with Swift.

**Comment by ADKaster** [comment]
Hmm okay, maybe my dev environment is less setup than I thought.

I have clangd installed, but it is disabled in my workspace.

I have Swift-OSS `main-snapshot-2024-09-18` installed using `swiftly`

I have a source file whose compile commands look like this:

```
{
  "directory": "/home/andrew/ladybird-org/ladybird-browser/Build/ladybird",
  "command": "/home/andrew/.local/bin/swiftc -j 32 -num-threads 32 -c -DENABLE_COMPILETIME_FORMAT_CHECK -DLIBGFX_USE_SWIFT -DLibGfx_EXPORTS -DSK_CODEC_DECODES_BMP -DSK_CODEC_DECODES_GIF -DSK_CODEC_DECODES_ICO -DSK_CODEC_DECODES_JPEG -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_RAW -DSK_CODEC_DECODES_WBMP -DSK_CODEC_DECODES_WEBP -DSK_DISABLE_TRACING -DSK_ENABLE_AVX512_OPTS -DSK_ENABLE_PRECOMPILE -DSK_FONTMGR_ANDROID_AVAILABLE -DSK_FONTMGR_FONTCONFIG_AVAILABLE -DSK_FONTMGR_FREETYPE_DIRECTORY_AVAILABLE -DSK_FONTMGR_FREETYPE_EMBEDDED_AVAILABLE -DSK_FONTMGR_FREETYPE_EMPTY_AVAILABLE -DSK_GAMMA_APPLY_TO_A8 -DSK_GANESH -DSK_GL -DSK_HAS_WUFFS_LIBRARY -DSK_R32_SHIFT=16 -DSK_SUPPORT_PDF -DSK_TYPEFACE_FACTORY_FREETYPE -DSK_USE_PERFETTO -DSK_USE_VMA -DSK_VULKAN -DSK_XML -D_FILE_OFFSET_BITS=64 -parse-as-library -emit-module -emit-module-path swift/Gfx.swiftmodule -module-name Gfx -module-link-name lagom-gfx -O -g -incremental -Xcc -Wall -Xcc -Wextra -Xcc -fno-exceptions -Xcc -ffp-contract=off -Xcc -Wcast-qual -Xcc -Wformat=2 -Xcc -Wimplicit-fallthrough -Xcc -Wmissing-declarations -Xcc -Wsuggest-override -Xcc -Wno-invalid-offsetof -Xcc -Wno-unknown-warning-option -Xcc -Wno-unused-command-line-argument -Xcc -Werror -Xcc -fconstexpr-steps=16777216 -Xcc -Wmissing-prototypes -Xcc -Wno-implicit-const-int-float-conversion -Xcc -Wno-user-defined-literals -Xcc -Wno-vla-cxx-extension -Xcc -Wno-unqualified-std-cast-call -Xcc -fno-semantic-interposition -Xcc -fvisibility-inlines-hidden -Xcc -fstack-protector-strong -Xcc -fstrict-flex-arrays=2 -Xcc -Wno-maybe-uninitialized -Xcc -Wno-shorten-64-to-32 -Xcc -fsigned-char -Xcc -ggnu-pubnames -Xcc -fPIC -Xcc -O2 -Xcc -g1 -Xcc -Wno-overloaded-virtual -Xcc -Wno-unused-private-field -Xcc -ivfsoverlay/home/andrew/ladybird-org/ladybird-browser/Build/ladybird/vfs_overlays/LibGfx_vfs_overlay.yaml -Xcc -std=c++23 -cxx-interoperability-mode=default -Xcc -ivfsoverlay/home/andrew/ladybird-org/ladybird-browser/Build/ladybird/vfs_overlays/AK_vfs_overlay.yaml -DJXL_STATIC_DEFINE -DHWY_STATIC_DEFINE -DJXL_CMS_STATIC_DEFINE -output-file-map Lagom/Userland/Libraries/LibGfx/CMakeFiles/LibGfx.dir/RelWithDebInfo/output-file-map.json -I /home/andrew/ladybird-org/ladybird-browser -I /home/andrew/ladybird-org/ladybird-browser/Userland/Services -I /home/andrew/ladybird-org/ladybird-browser/Userland/Libraries -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/Lagom -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/Lagom/Userland/Services -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/Lagom/Userland/Libraries -I /home/andrew/.local/share/swiftly/toolchains/main-snapshot-2024-09-18/usr/include -I /home/andrew/ladybird-org/ladybird-browser/Meta/Lagom/../.. -I /home/andrew/ladybird-org/ladybird-browser/Meta/Lagom/../../Userland -I /home/andrew/ladybird-org/ladybird-browser/Meta/Lagom/../../Userland/Libraries -I /home/andrew/ladybird-org/ladybird-browser/Meta/Lagom/../../Userland/Services -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/Lagom/Userland/Libraries/LibGfx/include -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/swift -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/Lagom/AK/include -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/vcpkg_installed/x64-linux/include -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/vcpkg_installed/x64-linux/lib/pkgconfig/../../include -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/vcpkg_installed/x64-linux/include/webp -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/vcpkg_installed/x64-linux/include/skia -I /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/vcpkg_installed/x64-linux/include/harfbuzz /home/andrew/ladybird-org/ladybird-browser/Userland/Libraries/LibGfx/Color.swift",
  "file": "/home/andrew/ladybird-org/ladybird-browser/Userland/Libraries/LibGfx/Color.swift",
  "output": "Lagom/Userland/Libraries/LibGfx/CMakeFiles/LibGfx.dir/Color.swift.o"
},
```

The important lines here is this:

` -cxx-interoperability-mode=default -Xcc -ivfsoverlay/home/andrew/ladybird-org/ladybird-browser/Build/ladybird/vfs_overlays/AK_vfs_overlay.yaml`

I am passing the location of `AK/module.modulemap` using the clang vfs overlay feature to swiftc via an -Xcc option.

In the `output` in VsCode, I have the following messages:

Swift:
```
15:47:39: SourceKit-LSP setup
15:47:39: Failed to find /home/andrew/.local/share/swiftly/toolchains/main-snapshot-2024-09-18/usr/bin/lldb-vscode
15:47:40: focus: undefined
```

SourceKit-LSP:
```
/home/andrew/ladybird-org/ladybird-browser/Userland/Libraries/LibGfx/Color.swift:7:8: error: no such module 'AK'
import AK
       ^
<repeated a dozen times>
```

Perhaps this isn't really a SourceKit-LSP problem? :sweat_smile: .

All I know is, I get a red squiggle for `import AK`, where the contents of `/home/andrew/ladybird-org/ladybird-browser/Build/ladybird/vfs_overlays/AK_vfs_overlay.yaml` is a generated file:

```yaml
roots:
- external-contents: /home/andrew/ladybird-org/ladybird-browser/Build/ladybird/Lagom/AK/module/module.modulemap
  name: /home/andrew/ladybird-org/ladybird-browser/AK/module.modulemap
  type: file
use-external-names: false
version: 0
```

That has the name "<source-root>/AK/module.modulemap" and points to a generated modulemap file :)

I copied this approach from foundationdb fwiw. https://github.com/apple/foundationdb/blob/70f9440e7deb104e5903fbc8cff2e82d47fc2668/cmake/GenerateModulemap.cmake

**Comment by ADKaster** [comment]
... I typed all that, and it seems to work after doing a build and letting sourcekit-lsp chill for a few minutes. Sorry for the noise!
