### ISSUE TITLE
Tests in extensions aren't listed correctly

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/sourcekit-lsp#1769]
**Describe the bug**
Tests in extensions of XCTest classes don't get listed under their class name in the TestExplorer and they don't run when you select them.

**To Reproduce**
1. Open https://github.com/soto-project/soto in VSCode
2. Open Tests/SotoTests/Services/S3/S3ExtensionTests.swift
3. The tests in here are listed at the bottom of TestExplorer outside of S3Tests class

**Expected behavior**
All tests are listed in the correct place and run

**Environment**
 - OS: Sequoia 15.0
 - Swift version: swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
 - Visual Studio Code version: 1.93.1
 - vscode-swift version: 1.11.2

**Comment by plemarquand** [comment]
Fixed in #1218
