### ISSUE TITLE
Sourcekit error on MacBook Pro - macOS 14.7 (23H124)

### ISSUE THREAD

**Issue by Asif2201** [swiftlang/sourcekit-lsp#1791]
I am trying to use VSCode to develop Swift application.
[Diagnose Bundle.md](https://github.com/user-attachments/files/17563589/Diagnose.Bundle.md)

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://138873093

**Comment by ahoppen** [comment]
@Asif2201 Could you please elaborate what the issue that you’re seeing is. Also, you attached the `Diagnose Bundle.md` documentation file, not the diagnose bundle you created locally and probably wanted to attach. Please re-open this issue when you’re able to provide that information.
