### ISSUE TITLE
How to disable automatic formatting on save?

### ISSUE THREAD

**Issue by diocletiann** [swiftlang/sourcekit-lsp#1810]
I don't see a setting for this in `Configuration File.md`, not sure how to disable it.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://139407199

**Comment by ahoppen** [comment]
There’s a VS Code setting for that (`"editor.formatOnSave"`), it’s not a SourceKit-LSP setting.

**Comment by diocletiann** [comment]
> There’s a VS Code setting for that (`"editor.formatOnSave"`), it’s not a SourceKit-LSP setting.

Sorry, I thought it was disabled in neovim (and happening anyway), it's off now. Thanks.
