### ISSUE TITLE
`sourcekit-lsp --version` please?

### ISSUE THREAD

**Issue by MahdiBM** [swiftlang/sourcekit-lsp#1830]
### Swift version

swiftlang-6.0.2.1.2 clang-1600.0.26.4

### Platform

macOS 15

### Editor

irrelevant 

### Description

`sourcekit-lsp --version` does not work. Neither do `sourcekit-lsp -version` or `sourcekit-lsp version`.

### Steps to Reproduce

Simply try.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://140040940

**Comment by MahdiBM** [comment]
Optimally it would include the commit SHA from this repo.

**Comment by ahoppen** [comment]
Duplicate of https://github.com/swiftlang/sourcekit-lsp/issues/1424
