### ISSUE TITLE
SourceKit-LSP not publishing diagnostics on Windows

### ISSUE THREAD

**Issue by award999** [swiftlang/sourcekit-lsp#1855]
### Swift version

Swift version 6.0.2 (swift-6.0.2-RELEASE)

### Platform

Windows 11

### Editor

vscode-swift extension

### Description

https://github.com/swiftlang/vscode-swift/issues/1226 was reported to vscode-swift repo. I am able to reproduce it on Windows with both the ARM64 and x86_64 toolchains downloaded off swift.org. Finding references and go to definition requests are working, the vscode-swift extension just isn't getting diagnostics.

### Steps to Reproduce

1. Open a project in the vscode-swift extension
2. Write some bad code that should produce a compiler error:
```
let f =1
f = 2
```
3. Notice that no diagnostics show
4. Run a vscode build task and see that the `swiftc` diagnostics show up
5. Fix the error, notice it doesn't get cleared

### Logging

attached log for simple project created with "swift init"
[sourcekit-lsp diagnostics.zip](https://github.com/user-attachments/files/18028819/sourcekit-lsp.diagnostics.zip)

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://141001203
