### ISSUE TITLE
CompilationDatabaseBuildSystem should account for working directory

### ISSUE THREAD

**Issue by bkolb** [swiftlang/sourcekit-lsp#1856]
### Swift version

swiftlang-6.1.0.101.24 clang-1700.0.4.22

### Platform

macOS

### Editor

VSCode

### Description

I have configured sourcekit-lsp in VSCode to use compile-commands extracted from bazel. 
Trying to resolve reverse references fails. The reason is that my path pointing to the global index is relative to the working directory. Once converted to an absolute path, it works.
The candidate could be here: https://github.com/swiftlang/sourcekit-lsp/blob/main/Sources/BuildSystemIntegration/CompilationDatabaseBuildSystem.swift#L91-L109

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://141004197
