### ISSUE TITLE
Background Indexing edits Package.resolved

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/sourcekit-lsp#1878]
### Swift version

Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)

### Platform

macOS

### Editor

VSCode

### Description

The background indexing process edits the Package.resolved file. If background indexing disagrees with the build process on the contents of this file then the auto resolve from VS Code will end up fighting with the background indexing about the correct state. 

Of course they should agree on the state of the Package.resolved file but that isn't the case at the moment. See #1877 

### Steps to Reproduce

See #1877 for reproduction steps.

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://141118757

**Comment by ahoppen** [comment]
This is the same underlying issue as https://github.com/swiftlang/sourcekit-lsp/issues/1877 (`workspace-state.json` being per scratch dir and `Package.resolved` being global for the package). Let’s use #1877 to track this issue.

**Comment by adam-fowler** [comment]
I think they are two issues. The solution to #1877 will not necessarily be the solution to this.

**Comment by ahoppen** [comment]
It should be. The problem is that we’re not picking up the edit state for the dependencies in `index-build`.
