### ISSUE TITLE
Relative paths in compile_commands.json are not resolved

### ISSUE THREAD

**Issue by bnbarham** [swiftlang/sourcekit-lsp#1893]
### Swift version

swift-DEVELOPMENT-SNAPSHOT-2024-12-16-a

### Platform

macOS

### Editor

Visual Studio Code

### Description

Relative paths inside commands of `compile_commands.json` are not resolved. Depending on exactly what that path is, that can result in a complete lack of functionality.

### Steps to Reproduce

1. Clone https://gitea.com/TeamPuzel/BlockGameSwift.git
2. Add a fetch for SDL in the CMakeLists.txt:
```
include(FetchContent)
find_package(SDL3 CONFIG)
if(NOT SDL3_FOUND)
  FetchContent_Declare(SDL3
    GIT_REPOSITORY https://github.com/libsdl-org/SDL.git
    GIT_TAG main)
  FetchContent_MakeAvailable(SDL3)
endif()
```
3. Configure and build into eg. `build`
4. Note that the path for `-output-file-map` is relative
5. Semantic functionality doesn't work

**Comment by ahoppen** [comment]
Synced to Apple’s issue tracker as rdar://141662643

**Comment by bnbarham** [comment]
I can't reproduce this, it could be that the failure I was actually having was that I had a workspace in /tmp and we had /tmp + /private/tmp mismatches.

We do already pass `-working-directory` through to sourcekitd and that does work as far as I can tell.
