### ISSUE TITLE
Support for Xcode projects

### ISSUE THREAD

**Issue by yaroslavyaroslav** [swiftlang/sourcekit-lsp#730]
I've read the readme about Indexing while building technique, so I've got the point. And also I'm aware that `swift` itself has a limited support for Xcode projects by purpose. 

Anyway, is there a way to index [use Xcode index somehow] the code by `xcodebuild`, to make LSP work with it at least in a less limited way?

UPD: here's the best solution that I was able to find: [xcode-build-server](https://github.com/SolaWing/xcode-build-server) it's still quite limited so far, but yet it's reliable and straightforward in its usage.

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://108104659

**Comment by yaroslavyaroslav** [comment]
@konrad1977 to you for sharing that hack! Didn't knew about that. Could you please point me out to the line in your plug-in that passes target to the lsp server?

Ps: unfortunately I'm not a emacs under, but I guess I would be able to understand the logic behind the code.

**Comment by konrad1977** [comment]
-Xswiftc "-sdk" -Xswiftc "xcrun --sdk iphonesimulator --show-sdk-path" 
-Xswiftc "-target" -Xswiftc "arm_64-apple-ios16.2-simulator"

This thread is a good starting point:
https://forums.swift.org/t/how-to-use-sourcekit-lsp-with-ios-projects/28273

**Comment by yaroslavyaroslav** [comment]
@konrad1977 Thank you so much for that link. There I was found [xcode-build-server](https://github.com/SolaWing/xcode-build-server) utility. Though it's manual it fits my needs.

I would not close this issue though, since I do not consider that utility as a comprehensive solution.

**Comment by yaroslavyaroslav** [comment]
Hey, @konrad1977 sorry to bother you after such a long time.

I've tried just now your approach to make `sourcekit-lsp` working, and it works great at my side. But there's just one issue I've faced: it's unable to fetch data from any dependency package that I have.

I've looked at a glance into your command that is copying `xcodebuild` derived data into a SPM `.build` folder and as far as I can tell there's no dependencies handling here `rsync -ua --include='*/' --delete --include='*.swiftmodule' --exclude '*'`.

Do I missing something or is it made such by purpose?

Worth to say I'm having no clue where these dependencies are stored within derived data, so for me this is research yet to be done.

**Comment by ahoppen** [comment]
SourceKit-LSP exposes its build system integration to external build systems via the build server protocol now, as described in [Implementing a BSP server.md](https://github.com/swiftlang/sourcekit-lsp/blob/main/Contributor%20Documentation/Implementing%20a%20BSP%20server.md). Please file feedback at https://feedbackassistant.apple.com/ for Xcode-specific feature requests, like integration with SourceKit-LSP via BSP.
