### ISSUE TITLE
Add support for selecting SwiftSDKs

### ISSUE THREAD

**Issue by adam-fowler** [swiftlang/sourcekit-lsp#786]
Now that the [SwiftSDKs](https://github.com/apple/swift-evolution/blob/main/proposals/0387-cross-compilation-destinations.md) proposal has been accepted, SourceKit-LSP should add support for the SwiftPM command line parameter: `--swift-sdk`. So the user can select a SwiftSDK in a similar manner to how they would with SwiftPM.

**Comment by adam-fowler** [comment]
@MaxDesiatov

**Comment by ahoppen** [comment]
Tracked in Apple’s issue tracker as rdar://113099964
